travis:
  secure:
    BINSTAR_TOKEN: qdBDP979efiCc/58MFp29ZigvBO4vLJk5nMNrD2dcEmrg0vRJJh/FJGGK0cL6LLEQhKvctRPmwQ/ikso0Ni1fRJ20YEoOz9+V5gPGHt3reKzWarM7bF4EK4yc1gskHHStRQrH25CJ6RUwUYk5lNoa6gtw79QaT1gAJKcpI5dWwo1qWRGAtM6Th9kqA0XNgKs63SaHPmap7pjshm5s/iIyeiE54Pnw/qMkuTgFC2XSwaVeH8eEZPRrJGm5UPko+bWBKf3k4grmtluAbeKkxqMoN+DUd37lxYC03GuLWtBjZXmJz17jEIjz9xzJ/rC/pLmr6sp56e4P5MFIrDtA52x8d+HliANE+VdLM/57x4LFhFCNDMCOT9xRll7rkzWcmmbjD7U4jmlTgPAeyh5r+Y6R6S90iGA66EbiVCALNcTyAUUM5c0ax9ljjGJh69CK04vch+Cd6KoxCZu0/gaKv8LxjxM0FGXBycunEIidkXCgceTmsVpa9l2kBM8cq6V1d9BwtbM0DPu2Tp6BMBj8NdZxREZ2XpcobyaUTxfNKyI7igbxjgtQt2r5kdRqYmkQwdoX809nOZ7s7IJkO/DzyCVdqHjVWDEl3x7NUOmq/I+MVFDzbd7h4YZepGRIPuo1x2wEHlSogRqgMjMinOK201DXdXW0twJePy6nZh11qHQzzI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
